abstract final class CurrencyFlagAssets {
  static const directory = 'assets/images/currency_flags';
  static const fallbackAssetPath = '$directory/xx.svg';

  /// Maps each bundled currency to the Circle Flags source artwork used for it.
  ///
  /// The checked-in asset is named after the currency code rather than this
  /// source code, so callers never need to understand country-code mappings.
  static const sourceFlagCodeByCurrencyCode = <String, String>{
    'AED': 'ae',
    'AFN': 'af',
    'ALL': 'al',
    'AMD': 'am',
    'ARS': 'ar',
    'AUD': 'au',
    'AZN': 'az',
    'BAM': 'ba',
    'BDT': 'bd',
    'BGN': 'bg',
    'BHD': 'bh',
    'BIF': 'bi',
    'BND': 'bn',
    'BOB': 'bo',
    'BRL': 'br',
    'BWP': 'bw',
    'BYN': 'by',
    'BZD': 'bz',
    'CAD': 'ca',
    'CDF': 'cd',
    'CHF': 'ch',
    'CLP': 'cl',
    'CNY': 'cn',
    'COP': 'co',
    'CRC': 'cr',
    'CVE': 'cv',
    'CZK': 'cz',
    'DJF': 'dj',
    'DKK': 'dk',
    'DOP': 'do',
    'DZD': 'dz',
    'EEK': 'ee',
    'EGP': 'eg',
    'ERN': 'er',
    'ETB': 'et',
    'EUR': 'eu',
    'GBP': 'gb',
    'GEL': 'ge',
    'GHS': 'gh',
    'GNF': 'gn',
    'GTQ': 'gt',
    'HKD': 'hk',
    'HNL': 'hn',
    'HRK': 'hr',
    'HUF': 'hu',
    'IDR': 'id',
    'ILS': 'il',
    'INR': 'in',
    'IQD': 'iq',
    'IRR': 'ir',
    'ISK': 'is',
    'JMD': 'jm',
    'JOD': 'jo',
    'JPY': 'jp',
    'KES': 'ke',
    'KHR': 'kh',
    'KMF': 'km',
    'KRW': 'kr',
    'KWD': 'kw',
    'KZT': 'kz',
    'LBP': 'lb',
    'LKR': 'lk',
    'LTL': 'lt',
    'LVL': 'lv',
    'LYD': 'ly',
    'MAD': 'ma',
    'MDL': 'md',
    'MGA': 'mg',
    'MKD': 'mk',
    'MMK': 'mm',
    'MOP': 'mo',
    'MUR': 'mu',
    'MXN': 'mx',
    'MYR': 'my',
    'MZN': 'mz',
    'NAD': 'na',
    'NGN': 'ng',
    'NIO': 'ni',
    'NOK': 'no',
    'NPR': 'np',
    'NZD': 'nz',
    'OMR': 'om',
    'PAB': 'pa',
    'PEN': 'pe',
    'PHP': 'ph',
    'PKR': 'pk',
    'PLN': 'pl',
    'PYG': 'py',
    'QAR': 'qa',
    'RON': 'ro',
    'RSD': 'rs',
    'RUB': 'ru',
    'RWF': 'rw',
    'SAR': 'sa',
    'SDG': 'sd',
    'SEK': 'se',
    'SGD': 'sg',
    'SOS': 'so',
    'SYP': 'sy',
    'THB': 'th',
    'TND': 'tn',
    'TOP': 'to',
    'TRY': 'tr',
    'TTD': 'tt',
    'TWD': 'tw',
    'TZS': 'tz',
    'UAH': 'ua',
    'UGX': 'ug',
    'USD': 'us',
    'UYU': 'uy',
    'UZS': 'uz',
    'VEF': 've',
    'VND': 'vn',
    'XAF': 'xx',
    'XOF': 'xx',
    'YER': 'ye',
    'ZAR': 'za',
    'ZMK': 'zm',
    'ZWL': 'zw',
  };

  static String forCurrencyCode(String currencyCode) {
    final normalizedCode = currencyCode.trim().toUpperCase();
    if (!sourceFlagCodeByCurrencyCode.containsKey(normalizedCode)) {
      return fallbackAssetPath;
    }

    return '$directory/${normalizedCode.toLowerCase()}.svg';
  }
}
